version: '3.8'

services:
  scanner_api:
    build: .
    container_name: scanner_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./reports:/app/reports
    network_mode: bridge
    